name: 'Slack Notification'
description: 'Send Slack notification with job status and workflow information'
inputs:
  webhook_url:
    description: 'Slack webhook URL'
    required: true
  job_status:
    description: 'Job status (success, failure, cancelled, etc.)'
    required: true
  repository:
    description: 'GitHub repository name'
    required: true
  branch:
    description: 'Git branch name'
    required: true
  actor:
    description: 'GitHub actor who triggered the workflow'
    required: true
  triggering_actor:
    description: 'User who triggered the workflow'
    required: false
    default: 'N/A'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'N/A'
  run_url:
    description: 'GitHub Actions run URL'
    required: true
  compare_url:
    description: 'Compare URL'
    required: false
    default: 'N/A'
  status_text:
    description: 'Custom status text to display'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Send Slack Notification
      shell: powershell
      run: |
        $status = '${{ inputs.job_status }}'
        $color = if ($status -eq "success") { "#36a64f"
        } elseif ($status -eq "failure")    { "#d00000"
        } elseif ($status -eq "cancelled")  { "#f0ba00"
        } else { "#000000" }

        $statusText = if ('${{ inputs.status_text }}' -ne '') { '${{ inputs.status_text }}' } else { $status }
        $message = "Status: $statusText`n"
        $message += "Repository: ${{ inputs.repository }}`n"
        $message += "Branch: ${{ inputs.branch }}`n"
        $message += "Trigger: ${{ inputs.actor }}`n"
        $message += "Users: ${{ inputs.triggering_actor }}`n"
        $message += "Commit: ${{ inputs.commit_message }}`n"
        $message += "Run: ${{ inputs.run_url }}`n"
        $message += "Compare: ${{ inputs.compare_url }}"

        Invoke-RestMethod -Uri '${{ inputs.webhook_url }}' -Method Post -Body (@{
          attachments = @(
            @{
              color = $color
              text = $message
            }
          )
        } | ConvertTo-Json) -ContentType 'application/json'

