name: 'Build Cocos Desktop'
description: 'Build cocos creator repositories for web-desktop'
inputs:
  game_id:
    description: 'Game ID'
    required: true
  cocos_version:
    description: 'Cocos Creator version path'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build web-desktop
      shell: cmd
      run: |
        echo cd game\%INPUT_GAME_ID% >> build.bat
        echo CALL %INPUT_COCOS_VERSION% --project . --build "stage=build;" >> build.bat

        CALL build.bat

        if %ERRORLEVEL%==36 exit 0
        if %ERRORLEVEL% NEQ 0 exit /b %ERRORLEVEL%
      env:
        INPUT_GAME_ID: ${{ inputs.game_id }}
        INPUT_COCOS_VERSION: ${{ inputs.cocos_version }}

