name: 'Cleanup Workspace'
description: 'Remove old workspace files'
runs:
  using: 'composite'
  steps:
    - name: Remove old workspace
      shell: powershell
      run: |
        cd ${{runner.workspace}}
        echo "Removing workspace: ${{runner.workspace}}\*"
        rm -Recurse -Force ${{runner.workspace}}\*

