name: 'Configure Git'
description: 'Configure Git URL with token'
inputs:
  github_deploy:
    description: 'GitHub deploy token'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Configure Git URL
      shell: cmd
      run: |
        git config --global url."https://%INPUT_GITHUB_DEPLOY%@github.com/".insteadOf "git@github.com:"
      env:
        INPUT_GITHUB_DEPLOY: ${{ inputs.github_deploy }}

