name: 'Clone Game Repositories'
description: 'Clone game repositories and get version hash'
inputs:
  github_deploy:
    description: 'GitHub deploy token'
    required: true
  game_id:
    description: 'Game ID'
    required: true
  branch:
    description: 'Branch name'
    required: true
  tag:
    description: 'Tag name to checkout. If provided, checks out the tag after cloning the branch.'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Clone game repositories
      shell: cmd
      run: |
        git clone --branch %INPUT_BRANCH% https://%INPUT_GITHUB_DEPLOY%@github.com/5G-Games/Games-%INPUT_GAME_ID% game\%INPUT_GAME_ID%
        cd game\%INPUT_GAME_ID%

        REM If tag is provided, checkout the tag
        IF NOT "%INPUT_TAG%"=="" (
            ECHO Checking out tag: %INPUT_TAG%
            git checkout tags/%INPUT_TAG%
        )

        for /f %%i in ('git rev-parse --short HEAD') do set GAME_HASH=%%i
        for /f %%i in ('git rev-parse --short HEAD:assets/base 2^>nul') do set BASE_HASH=%%i
        for /f %%i in ('git rev-parse --short HEAD:build-templates 2^>nul') do set TMPL_HASH=%%i
        cd ..\..
        if not defined GAME_HASH set GAME_HASH=N/A
        if not defined BASE_HASH set BASE_HASH=N/A
        if not defined TMPL_HASH set TMPL_HASH=N/A
        echo VERSION_HASH=%GAME_HASH%-%BASE_HASH%-%TMPL_HASH%>> %GITHUB_ENV%
      env:
        INPUT_GITHUB_DEPLOY: ${{ inputs.github_deploy }}
        INPUT_GAME_ID: ${{ inputs.game_id }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_TAG: ${{ inputs.tag }}
